[ 2024-06-11 10:56:24,367 ] 30 root - INFO - Initialized the ConnectSnowflake class
[ 2024-06-11 10:56:24,367 ] 399 snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.0, Platform: Windows-11-10.0.22631-SP0
[ 2024-06-11 10:56:24,367 ] 1239 snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[ 2024-06-11 10:56:25,946 ] 547 snowflake.connector.vendored.urllib3.connection - WARNING - Certificate did not match expected hostname: jjndjcw.dp86849.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
[ 2024-06-11 10:56:25,946 ] 824 snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'jjndjcw.dp86849.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=8327f913-a031-4c10-a573-c0ce7d6b712c&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=2cea4e42-3f23-48ea-93fc-8df053ccea16
[ 2024-06-11 10:56:26,633 ] 547 snowflake.connector.vendored.urllib3.connection - WARNING - Certificate did not match expected hostname: jjndjcw.dp86849.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
[ 2024-06-11 10:56:26,774 ] 1029 snowflake.connector.network - ERROR - Failed to get the response. Hanging? method: post, url: https://JJNDJCW.DP86849.snowflakecomputing.com:443/session/v1/login-request?request_id=8327f913-a031-4c10-a573-c0ce7d6b712c&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=2cea4e42-3f23-48ea-93fc-8df053ccea16, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.0', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "JJNDJCW", "LOGIN_NAME": "snagamolla06", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.0", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1935 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
[ 2024-06-11 10:56:28,541 ] 547 snowflake.connector.vendored.urllib3.connection - WARNING - Certificate did not match expected hostname: jjndjcw.dp86849.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
[ 2024-06-11 10:56:28,556 ] 824 snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'jjndjcw.dp86849.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=1d9590bf-3a82-4be6-a253-180f158c555f&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=7d443f9b-7b16-46bd-98ce-33913da7afd8
[ 2024-06-11 10:56:29,650 ] 547 snowflake.connector.vendored.urllib3.connection - WARNING - Certificate did not match expected hostname: jjndjcw.dp86849.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
[ 2024-06-11 10:56:29,666 ] 1029 snowflake.connector.network - ERROR - Failed to get the response. Hanging? method: post, url: https://JJNDJCW.DP86849.snowflakecomputing.com:443/session/v1/login-request?request_id=1d9590bf-3a82-4be6-a253-180f158c555f&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=7d443f9b-7b16-46bd-98ce-33913da7afd8, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.0', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "JJNDJCW", "LOGIN_NAME": "snagamolla06", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.0", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1935 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
[ 2024-06-11 10:56:29,681 ] 45 root - ERROR - Failed to connect to Snowflake: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
